# Generated by Django 5.2.17 on 2026-08-27 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_sw', models.TextField(blank=True)),
                ('intro_en', models.TextField(blank=True)),
                ('history_sw', models.TextField(blank=True)),
                ('history_en', models.TextField(blank=True)),
                ('vision_sw', models.TextField(blank=True)),
                ('vision_en', models.TextField(blank=True)),
                ('mission_sw', models.TextField(blank=True)),
                ('mission_en', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'About page',
                'verbose_name_plural': 'About page',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_sw', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_sw', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026)),
                ('month_index', models.PositiveSmallIntegerField(help_text='0 = January … 11 = December')),
                ('month_name_sw', models.CharField(max_length=20)),
                ('month_name_en', models.CharField(max_length=20)),
                ('date', models.PositiveSmallIntegerField(blank=True, help_text='Day of month, blank if undated', null=True)),
                ('title_sw', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['year', 'month_index', 'date'],
            },
        ),
        migrations.CreateModel(
            name='ChoirMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('voice_part', models.CharField(choices=[('soprano', 'Soprano'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass')], max_length=10)),
                ('joined_year', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['voice_part', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_sw', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('description_sw', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='ConstitutionArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_sw', models.CharField(max_length=255)),
                ('heading_en', models.CharField(max_length=255)),
                ('body_sw', models.TextField()),
                ('body_en', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Homily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_sw', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('reading_sw', models.CharField(max_length=255)),
                ('reading_en', models.CharField(max_length=255)),
                ('summary_sw', models.TextField()),
                ('summary_en', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Homilies',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='KinandaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sw', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('goal_amount', models.CharField(help_text='e.g. TZS 8,000,000', max_length=50)),
                ('raised_amount', models.CharField(help_text='e.g. TZS 3,200,000', max_length=50)),
                ('description_sw', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kinanda project',
                'verbose_name_plural': 'Kinanda project',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_sw', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('excerpt_sw', models.TextField()),
                ('excerpt_en', models.TextField()),
                ('body_sw', models.TextField()),
                ('body_en', models.TextField()),
            ],
            options={
                'verbose_name': 'News item',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sw', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('price', models.CharField(help_text='e.g. TZS 20,000', max_length=50)),
                ('description_sw', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='SSK', max_length=20)),
                ('name_sw', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('parish_sw', models.CharField(max_length=200)),
                ('parish_en', models.CharField(max_length=200)),
                ('diocese_sw', models.CharField(max_length=200)),
                ('diocese_en', models.CharField(max_length=200)),
                ('tagline_sw', models.CharField(max_length=200)),
                ('tagline_en', models.CharField(max_length=200)),
                ('founded_year', models.PositiveIntegerField(default=1975)),
                ('po_box', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('choir_photo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('registration_form_pdf', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SongCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name_sw', models.CharField(max_length=200)),
                ('name_en', models.CharField(max_length=200)),
                ('description_sw', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Song categories',
                'ordering': ['order', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role_sw', models.CharField(max_length=200)),
                ('role_en', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='choir.committee')),
            ],
            options={
                'ordering': ['committee', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption_sw', models.CharField(blank=True, max_length=255)),
                ('caption_en', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='choir.album')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_id', models.CharField(blank=True, max_length=32, null=True)),
                ('lyrics', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='choir.songcategory')),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
    ]
