# Generated by Django 5.2.17 on 2026-08-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choirmember',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Anwani ya makazi'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='agreed_to_constitution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='baptized',
            field=models.BooleanField(default=False, verbose_name='Ubatizo'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='birth_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='birth_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='communion',
            field=models.BooleanField(default=False, verbose_name='Komunyo'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='community',
            field=models.CharField(blank=True, max_length=200, verbose_name='Jumuiya'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Kipaimara'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Kike'), ('M', 'Kiume')], max_length=1),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='instrument_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='leader_comments',
            field=models.TextField(blank=True, verbose_name='Maoni/Maamuzi'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='married',
            field=models.BooleanField(default=False, verbose_name='Ndoa'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='other_talent',
            field=models.CharField(blank=True, max_length=255, verbose_name='Kipaji/karama nyingine'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='parish',
            field=models.CharField(blank=True, max_length=200, verbose_name='Parokia'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Namba ya simu'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='plays_instrument',
            field=models.BooleanField(default=False, verbose_name='Upigaji wa ala za muziki'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='processed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='received_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='Imepokelewa na'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='received_by_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cheo'),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choirmember',
            name='spiritual_gift',
            field=models.CharField(blank=True, max_length=255, verbose_name='Huduma ya kiroho/karama'),
        ),
    ]
